/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Tasks = IDL.Tuple(IDL.Bool, IDL.Bool, IDL.Bool);
export const ChallengeId = IDL.Variant({
  'moneySaving' : IDL.Null,
  'mentalHealth' : IDL.Null,
  'fitnessReset' : IDL.Null,
  'glowUp' : IDL.Null,
});
export const Time = IDL.Int;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'streak' : IDL.Nat,
          'completedTasks' : IDL.Vec(IDL.Tuple(IDL.Nat, Tasks)),
          'badges' : IDL.Vec(IDL.Text),
          'challengeId' : ChallengeId,
          'currentDay' : IDL.Nat,
          'points' : IDL.Nat,
          'startDate' : Time,
        }),
      ],
      ['query'],
    ),
  'getTodayCompletion' : IDL.Func([], [IDL.Nat, Tasks], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'resetChallenge' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startChallenge' : IDL.Func([ChallengeId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Tasks = IDL.Tuple(IDL.Bool, IDL.Bool, IDL.Bool);
  const ChallengeId = IDL.Variant({
    'moneySaving' : IDL.Null,
    'mentalHealth' : IDL.Null,
    'fitnessReset' : IDL.Null,
    'glowUp' : IDL.Null,
  });
  const Time = IDL.Int;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'streak' : IDL.Nat,
            'completedTasks' : IDL.Vec(IDL.Tuple(IDL.Nat, Tasks)),
            'badges' : IDL.Vec(IDL.Text),
            'challengeId' : ChallengeId,
            'currentDay' : IDL.Nat,
            'points' : IDL.Nat,
            'startDate' : Time,
          }),
        ],
        ['query'],
      ),
    'getTodayCompletion' : IDL.Func([], [IDL.Nat, Tasks], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'resetChallenge' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startChallenge' : IDL.Func([ChallengeId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };